_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 3
                - 16
                - 23
                - 24
                - 55
            "4": 3.10.13
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
T:
    value: 400
base_channels:
    value: 64
batch_size:
    value: 1024
beta_end:
    value: 0.02
beta_start:
    value: 0.0001
clip:
    value: 1
image_size:
    value: 28
in_channels:
    value: 1
learning_rate:
    value: 0.001
num_epochs:
    value: 100
out_channels:
    value: 1
time_emb_dim:
    value: 128
